// Package types defines the core data types used across the operator pipeline:
// DetectionInput (monitor → detection), DetectionResult (detection → remediation), ActionResult (remediation → metrics).
package types

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// DetectionSource indicates where the detection input originated (Kubernetes API or OpenTelemetry).
type DetectionSource string

const (
	DetectionSourceKubernetes DetectionSource = "kubernetes"
	DetectionSourceOTel       DetectionSource = "otel"
)

// Severity is the severity level of a detection or action (prioritization, escalation, notifications).
type Severity string

const (
	SeverityLow      Severity = "low"      // Informational, no immediate action needed
	SeverityMedium   Severity = "medium"   // Should investigate, but not urgent
	SeverityHigh     Severity = "high"     // Requires attention soon
	SeverityCritical Severity = "critical" // Immediate action required, may page on-call
)

// InstanceRole is the operator instance role when leader election is enabled (Leader runs pipeline and publishes tasks; Workers claim and execute them).
type InstanceRole string

const (
	RoleLeader InstanceRole = "leader"
	RoleWorker InstanceRole = "worker"
)

// ResourceReference identifies a Kubernetes resource (any API group/kind).
type ResourceReference struct {
	// APIVersion is the API version of the resource
	// Examples: "v1" (core), "apps/v1" (Deployment), "batch/v1" (Job)
	// For CRDs: "mycompany.io/v1" (custom resources)
	APIVersion string `json:"apiVersion"`

	// Kind is the kind of the resource
	// Examples: "Pod", "Deployment", "Service", "Node"
	// For CRDs: Any custom kind like "MyCustomResource"
	Kind string `json:"kind"`

	// Namespace is the namespace of the resource (empty for cluster-scoped)
	// Empty for cluster-scoped resources like Nodes, PersistentVolumes, CRDs
	Namespace string `json:"namespace"`

	// Name is the name of the resource
	// Must be unique within namespace+kind combination
	Name string `json:"name"`

	// UID is the unique identifier of the resource
	// Kubernetes assigns this, globally unique across cluster lifetime
	// Used to detect if a resource was deleted and recreated with same name
	UID string `json:"uid,omitempty"` // omitempty: don't serialize if empty
}

func (r ResourceReference) String() string {
	if r.Namespace != "" {
		return r.Namespace + "/" + r.Name
	}
	// Cluster-scoped resources (Nodes, PVs) just show name
	return r.Name
}

// Key returns a unique key for the resource (Kind/Namespace/Name). Uses name/namespace rather than UID so we track the same logical resource across recreates.
func (r ResourceReference) Key() string {
	return r.Kind + "/" + r.Namespace + "/" + r.Name
}

// DetectionInput is the payload from the monitor layer to the detection layer. Data holds the raw payload; scenarios match via CEL against it.
type DetectionInput struct {
	// ID is a unique identifier for this input
	// Generated by monitor layer (UUID), used for tracing/debugging
	// Example: "01J2K3M4N5P6Q7R8S9T0"
	ID string `json:"id"`

	// Source indicates where this input originated
	// One of: "kubernetes" or "otel"
	// This is a broad category - specific details in Labels and Data
	Source DetectionSource `json:"source"`

	// Resource is the Kubernetes resource this input relates to
	// Even OTel data is associated with a resource (the pod generating telemetry)
	// This allows scenarios to target specific resources or resource types
	Resource ResourceReference `json:"resource"`

	// Timestamp is when this input was created
	// time.Time in Go: includes location, serializes to RFC3339 in JSON
	Timestamp time.Time `json:"timestamp"`

	// Data contains the detection-specific data (unstructured, flexible)
	// map[string]interface{} = key-value pairs where values can be any type
	//
	// SCHEMA-DRIVEN: This is the data that CEL expressions evaluate against
	//
	// For Kubernetes sources, typically contains:
	//   - "status": full resource status object
	//   - "spec": full resource spec object
	//   - "metadata": resource metadata (labels, annotations)
	//
	// For OTel metrics:
	//   - "metricName": metric name (e.g., "http.server.duration")
	//   - "value": current value
	//   - "labels": metric labels/dimensions
	//   - "aggregation": type (avg, sum, rate)
	//
	// For OTel logs:
	//   - "severity": log severity (INFO, ERROR, etc.)
	//   - "body": log message text
	//   - "attributes": log attributes/fields
	//
	// For OTel traces:
	//   - "spanName": name of the span
	//   - "duration": span duration
	//   - "status": span status (OK, ERROR)
	//   - "attributes": span attributes
	// Data holds the raw payload; CEL expressions evaluate against it.
	Data map[string]interface{} `json:"data"`

	// Labels are additional metadata labels for filtering and routing
	// Prometheus-style key-value labels for flexible matching
	//
	// Common labels:
	//   - "eventType": "create", "update", "delete" (K8s events)
	//   - "telemetryType": "metric", "log", "trace" (OTel type)
	//   - "field": which field changed (for K8s updates)
	//   - Custom labels from resource labels or scenario configuration
	//
	// Scenarios can filter on labels before evaluating CEL conditions
	// Example: Only evaluate if labels["eventType"] == "update"
	//
	// omitempty: don't serialize if nil or empty map
	Labels map[string]string `json:"labels,omitempty"`
}

// DetectionResult is the output from Detection Layer to Remediation Layer
// This is emitted when a scenario's conditions and threshold are met
//
// Flow: Detection Engine → DetectionResult → Remediation Controller
type DetectionResult struct {
	// ID is a unique identifier for this result
	// Different from DetectionInput.ID (one input may trigger multiple scenarios)
	ID string `json:"id"`

	// ScenarioID is the ID of the matched scenario
	// References the scenario definition from ScenarioLibrary CRD
	// Example: "S1001" (CrashLoopBackOff scenario)
	ScenarioID string `json:"scenarioId"`

	// ScenarioName is the human-readable name of the scenario
	// For logging and notifications: "CrashLoopBackOff", "HighErrorRate"
	ScenarioName string `json:"scenarioName"`

	// Resource is the affected Kubernetes resource
	// The resource that needs remediation
	Resource ResourceReference `json:"resource"`

	// Severity of the detected issue
	// Determines escalation urgency and notification channels
	Severity Severity `json:"severity"`

	// FirstDetected is when this issue was first detected
	// Used to understand how long a problem has persisted
	FirstDetected time.Time `json:"firstDetected"`

	// LastDetected is when this issue was most recently detected
	// Updated each time the condition matches (for tracking frequency)
	LastDetected time.Time `json:"lastDetected"`

	// DetectionCount is how many times this has been detected
	// Within the scenario's time window (e.g., "3 times in 5 minutes")
	DetectionCount int `json:"detectionCount"`

	// ThresholdMet indicates if the detection threshold was met
	// true = ready for remediation; false = still counting
	ThresholdMet bool `json:"thresholdMet"`

	// Message is a human-readable description
	// Examples: "Pod crashed 3 times in 5 minutes", "Error rate exceeded 5%"
	Message string `json:"message"`

	// Context contains additional context for remediation
	// May include: original detection data, aggregated metrics, previous states
	// Helps remediation layer make smarter decisions
	Context map[string]interface{} `json:"context,omitempty"`

	// RecommendedActions are the actions to take
	// Comes from scenario definition, may be ordered
	// Remediation layer will execute these (after cooldown check)
	RecommendedActions []ActionConfig `json:"recommendedActions"`
}

// ============================================================================
// ACTION TYPES
// ============================================================================

// ActionType represents the type of remediation action
// These are the "verbs" the operator can perform
// Handler Pattern: each type has a corresponding handler implementation
//
// ActionType is the kind of remediation action (each has a handler in the action package).
type ActionType string

const (
	// ActionTypeScaleUp increases deployment replicas
	// Use case: High load, high CPU/memory, increased traffic
	ActionTypeScaleUp ActionType = "scaleUp"

	// ActionTypeScaleDown decreases deployment replicas
	// Use case: Overprovisioned, low load, cost optimization
	ActionTypeScaleDown ActionType = "scaleDown"

	// ActionTypeRestartPod deletes pod to trigger restart
	// Use case: Stuck pod, memory leak, transient errors
	ActionTypeRestartPod ActionType = "restartPod"

	// ActionTypeRollbackToPrevious rolls back to previous deployment revision
	// Use case: New deployment causing crashes, bugs in new version
	ActionTypeRollbackToPrevious ActionType = "rollback"

	// ActionTypeAdjustCPU modifies CPU limits/requests
	// Use case: CPU throttling, optimize resource allocation
	ActionTypeAdjustCPU ActionType = "adjustCPU"

	// ActionTypeAdjustMemory modifies memory limits/requests
	// Use case: OOMKilled, memory pressure, right-sizing
	ActionTypeAdjustMemory ActionType = "adjustMemory"

	// ActionTypeUpdateConfig updates ConfigMap values
	// Use case: Dynamic configuration changes for recovery
	ActionTypeUpdateConfig ActionType = "updateConfig"

	// ActionTypeRunJob creates a Kubernetes Job
	// Use case: Run cleanup script, database migration, repair task
	ActionTypeRunJob ActionType = "runJob"

	// ActionTypeNotify sends notification to external systems
	// Use case: Alert on-call, send to Slack/PagerDuty, create ticket
	ActionTypeNotify ActionType = "notify"
)

// ActionConfig defines a remediation action to execute
// This is the "instruction" for what action to take and how
//
// SCHEMA-DRIVEN: Actions defined in ScenarioLibrary CRD:
//
//	remediation:
//	  actions:
//	  - type: rollback
//	    order: 1
//	    params:
//	      condition: "hasRecentDeployment()"
//	  - type: notify
//	    order: 2
//	    params:
//	      severity: critical
type ActionConfig struct {
	// Type is the action type (which handler to use)
	Type ActionType `json:"type"`

	// Order determines execution order (lower = first)
	// Allows sequential execution: notify first, then rollback, then scale
	// Same order number = can execute in parallel
	Order int `json:"order"`

	// Params contains action-specific parameters
	// map[string]interface{} allows flexible parameters per action type
	//
	// Examples:
	//   scaleUp: {"increment": 2, "maxReplicas": 10}
	//   adjustMemory: {"increase": "25%", "maxValue": "2Gi"}
	//   notify: {"severity": "high", "channels": ["slack", "pagerduty"]}
	//   rollback: {"condition": "deploymentAge < 1h"}
	Params map[string]interface{} `json:"params,omitempty"`

	// Conditions are optional CEL conditions for execution
	// Example: only rollback if deployment is less than 1 hour old
	// Allows conditional logic: "if recent deployment then rollback else restart"
	//
	// CEL expression examples:
	//   - "hasRecentDeployment(resource)" - check deployment age
	//   - "resource.metadata.labels['canary'] == 'true'" - only canary pods
	//   - "detectionCount > 5" - only after multiple detections
	Conditions []ActionCondition `json:"conditions,omitempty"`
}

// ActionCondition defines a CEL condition for action execution
// Allows if/unless logic for smarter remediation
//
// SCHEMA-DRIVEN: Conditions evaluated at runtime via CEL
type ActionCondition struct {
	// Type is the condition type: "if" or "unless"
	// "if": execute action only if expression evaluates to true
	// "unless": execute action only if expression evaluates to false
	Type string `json:"type"`

	// Expression is the CEL condition expression
	// Has access to variables:
	//   - resource: ResourceReference of affected resource
	//   - detectionCount: number of times detected
	//   - context: additional context data
	//
	// Examples:
	//   - "deploymentAge(resource) < duration('1h')" - recent deployment
	//   - "detectionCount > 5" - many detections
	//   - "resource.metadata.labels['env'] == 'prod'" - production only
	Expression string `json:"expression"`
}

// ActionStatus represents the status of an action execution
// Tracks the lifecycle of an action attempt
type ActionStatus string

const (
	ActionStatusPending   ActionStatus = "pending"   // Queued, not started yet
	ActionStatusRunning   ActionStatus = "running"   // Currently executing
	ActionStatusSucceeded ActionStatus = "succeeded" // Completed successfully
	ActionStatusFailed    ActionStatus = "failed"    // Failed to execute
	ActionStatusSkipped   ActionStatus = "skipped"   // Skipped (cooldown, condition)
	ActionStatusDryRun    ActionStatus = "dryRun"    // Dry-run mode (logged, not executed)
)

// ActionResult is the result of executing a remediation action
// This is the "receipt" of what was done
//
// Flow: Action Handler → ActionResult → (metrics, logs, possibly next action)
type ActionResult struct {
	// ID is a unique identifier for this result
	ID string `json:"id"`

	// DetectionResultID links back to the detection that triggered this
	// Allows tracing: DetectionInput → DetectionResult → ActionResult
	DetectionResultID string `json:"detectionResultId"`

	// ScenarioID is the scenario that was triggered
	// For metrics aggregation by scenario
	ScenarioID string `json:"scenarioId"`

	// Resource is the affected Kubernetes resource
	// What resource did we act on?
	Resource ResourceReference `json:"resource"`

	// Action is the action that was executed (includes type and params)
	// Full action config for audit trail
	Action ActionConfig `json:"action"`

	// Status is the result status (succeeded, failed, skipped, etc.)
	Status ActionStatus `json:"status"`

	// StartTime is when the action started
	// For measuring action duration
	StartTime time.Time `json:"startTime"`

	// EndTime is when the action completed
	// Duration = EndTime - StartTime
	EndTime time.Time `json:"endTime"`

	// Message is a human-readable result description
	// Examples: "Scaled deployment from 2 to 4 replicas", "Rollback completed"
	Message string `json:"message"`

	// Error contains error details if the action failed
	// Only populated if Status == ActionStatusFailed
	Error string `json:"error,omitempty"`

	// Changes describes what was changed
	// Allows tracking exact modifications for audit and rollback
	// Example: [{"field": "spec.replicas", "oldValue": "2", "newValue": "4"}]
	Changes []ResourceChange `json:"changes,omitempty"`
}

// ResourceChange describes a change made to a resource
// Provides detailed audit trail of modifications
type ResourceChange struct {
	// Field is the field that was changed
	// JSONPath-style: "spec.replicas", "spec.template.spec.containers[0].resources.limits.memory"
	Field string `json:"field"`

	// OldValue is the previous value (if known)
	// String representation for simplicity
	OldValue string `json:"oldValue,omitempty"`

	// NewValue is the new value
	// What we changed it to
	NewValue string `json:"newValue"`
}

// ============================================================================
// STATE TRACKING TYPES
// ============================================================================

// DetectionState tracks the state of a detection per scenario+resource
// This is in-memory state used by Detection Engine for threshold counting
//
// Example: Scenario "CrashLoopBackOff" needs "3 crashes in 5 minutes"
// DetectionState tracks: first crash time, count, whether threshold is met
//
// SCHEMA-DRIVEN: Threshold configuration comes from ScenarioLibrary CRD:
//
//	detection:
//	  threshold:
//	    count: 3
//	    window: 15m
type DetectionState struct {
	// ScenarioID is the scenario this state is for
	// Key component: state is per-scenario
	ScenarioID string `json:"scenarioId"`

	// Resource is the resource this state is for
	// Key component: state is per-resource
	// Together: ScenarioID + Resource = unique state key
	Resource ResourceReference `json:"resource"`

	// FirstDetected is when the condition was first detected
	// Marks the start of the counting window
	FirstDetected time.Time `json:"firstDetected"`

	// LastDetected is the most recent detection
	// Updated each time condition matches
	LastDetected time.Time `json:"lastDetected"`

	// DetectionCount is the number of detections in the current window
	// Example: if threshold is "3 in 5 minutes", this counts up to 3
	DetectionCount int `json:"detectionCount"`

	// ThresholdMet indicates if the threshold has been met
	// true = ready to emit DetectionResult to remediation layer
	ThresholdMet bool `json:"thresholdMet"`

	// WindowStart is the start of the current counting window
	// Used to expire old detections: if now - WindowStart > scenario's threshold window, reset.
	// The window duration is defined on the scenario (detection.ThresholdConfig.Window or
	// DetectionSpec.Threshold.Window in the CRD), not on this state.
	WindowStart time.Time `json:"windowStart"`
}

// RemediationState tracks the state of remediation per scenario+resource
// This is in-memory state used by Remediation Controller for cooldown/retry tracking
//
// Example: After restarting a pod, don't restart again for 15 minutes (cooldown)
// RemediationState tracks: last action time, retry count, cooldown expiry
//
// SCHEMA-DRIVEN: Cooldown configuration comes from config or ScenarioLibrary:
//
//	remediation:
//	  cooldown: 15m
//	  maxAttempts: 3
type RemediationState struct {
	// ScenarioID is the scenario this state is for
	ScenarioID string `json:"scenarioId"`

	// Resource is the resource this state is for
	Resource ResourceReference `json:"resource"`

	// LastRemediation is when the last action was executed
	// Used to calculate time since last action (for cooldown check)
	LastRemediation time.Time `json:"lastRemediation"`

	// RemediationCount is the number of consecutive remediation attempts
	// Increments on each attempt, resets on success or after long period
	// Used for: "if tried 3 times and still failing, escalate"
	RemediationCount int `json:"remediationCount"`

	// CooldownUntil is when the cooldown expires
	// Set after each remediation: CooldownUntil = now + cooldown duration
	// Prevents "remediation storms" (repeated actions too quickly)
	CooldownUntil time.Time `json:"cooldownUntil"`

	// Escalated indicates if this has been escalated
	// Once escalated, stop auto-remediation (needs human intervention)
	Escalated bool `json:"escalated"`

	// LastActionStatus is the status of the last action
	// Helps decide: if last action failed, maybe try different action
	LastActionStatus ActionStatus `json:"lastActionStatus"`
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

// StateKey generates a unique key for state storage
// Used by both DetectionState and RemediationState maps
//
// Parameters:
//
//	scenarioID - The scenario identifier (from ScenarioLibrary)
//	resource - The Kubernetes resource reference
//
// Returns:
//
//	String key in format: "scenarioID/Kind/Namespace/Name"
//
// This is a PACKAGE-LEVEL FUNCTION (not a method on a type)
// Called as: types.StateKey(id, ref)
func StateKey(scenarioID string, resource ResourceReference) string {
	// Combine scenario ID with resource key
	// Ensures state is isolated per scenario+resource combination
	// Different scenarios can track the same resource independently
	return scenarioID + "/" + resource.Key()
}

// ============================================================================
// KUBERNETES INTEGRATION TYPES
// ============================================================================

// OwnerInfo describes the owner of a resource (e.g. Pod → ReplicaSet → Deployment). Used to resolve the workload for remediation.
type OwnerInfo struct {
	// APIVersion of the owner
	// Examples: "apps/v1", "batch/v1", custom API groups
	APIVersion string `json:"apiVersion"`

	// Kind of the owner (e.g., "ReplicaSet", "Deployment", "StatefulSet")
	Kind string `json:"kind"`

	// Name of the owner
	Name string `json:"name"`

	// UID of the owner (unique identifier)
	UID string `json:"uid"`
}

// ToOwnerReference returns the K8s OwnerReference for this owner.
func (o OwnerInfo) ToOwnerReference() metav1.OwnerReference {
	return metav1.OwnerReference{
		APIVersion: o.APIVersion,
		Kind:       o.Kind,
		Name:       o.Name,
		UID:        types.UID(o.UID), // Convert string to types.UID
	}
}

// ============================================================================
// SCHEMA-DRIVEN ARCHITECTURE NOTES
// ============================================================================
//
// HOW DETECTION WORKS (without DetectionType enum):
//
// 1. MONITOR LAYER (k8s_monitor.go, otel_receiver.go):
//    - Watches resources (Pods, Deployments, Events, etc.)
//    - Converts K8s objects to DetectionInput with full data in Data map
//    - No need to know which scenarios exist
//
// 2. DETECTION LAYER (detection/engine.go):
//    - Loads scenarios from ScenarioLibrary CRDs
//    - For each DetectionInput, finds matching scenarios by:
//      a. Source match (kubernetes vs otel)
//      b. Resource kind match (Pod, Deployment, etc.)
//      c. Label match (optional filters)
//    - Evaluates CEL expression against DetectionInput.Data
//    - Tracks state and threshold
//
// 3. EXAMPLE SCENARIO EVALUATION:
//
//    Scenario (from CRD):
//      detection:
//        source: kubernetes
//        resource: {kind: Pod}
//        condition: |
//          has(data.status.containerStatuses) &&
//          data.status.containerStatuses.exists(cs,
//            has(cs.state.waiting) &&
//            cs.state.waiting.reason == "CrashLoopBackOff"
//          )
//
//    DetectionInput:
//      {
//        "source": "kubernetes",
//        "resource": {kind: "Pod", name: "my-pod"},
//        "data": {
//          "status": {
//            "containerStatuses": [{
//              "state": {"waiting": {"reason": "CrashLoopBackOff"}}
//            }]
//          }
//        }
//      }
//
//    CEL Evaluation:
//      - Engine compiles CEL expression from scenario
//      - Evaluates expression with DetectionInput.Data as "data" variable
//      - Returns true if condition matches
//      - Updates DetectionState, checks threshold
//      - Emits DetectionResult if threshold met
//
// BENEFITS OF THIS APPROACH:
//   + No code changes to add new resource types (just apply CRD)
//   + Works with any Kubernetes resource including CRDs
//   + User-defined scenarios (ops teams can define their own)
//   + GitOps-friendly (scenarios in Git, applied via CI/CD)
//   + Flexible conditions (CEL is powerful expression language)
//   + Runtime validation (CEL expressions validated at scenario load)
//
// TRADEOFFS:
//   - Less compile-time safety (CEL errors at runtime)
//   - Slightly slower (CEL interpretation vs native Go)
//   - Requires CEL knowledge for scenario authors
//   - Debugging CEL expressions harder than Go code
//
// MITIGATION:
//   + Validate CEL at scenario load time (fail fast)
//   + Provide CEL helper functions (hasRecentDeployment, etc.)
//   + Comprehensive CEL error messages with context
//   + Example scenarios as templates
//   + Testing framework for scenarios
