{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "selfhealing-operator.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ include "selfhealing-operator.namespace" . }}
  labels:
    {{- include "selfhealing-operator.labels" . | nindent 4 }}
{{- end }}
