//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 Ariadna Ops.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionSpec.
func (in *ActionSpec) DeepCopy() *ActionSpec {
	if in == nil {
		return nil
	}
	out := new(ActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRemediationPolicy) DeepCopyInto(out *ClusterRemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRemediationPolicy.
func (in *ClusterRemediationPolicy) DeepCopy() *ClusterRemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterRemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRemediationPolicyList) DeepCopyInto(out *ClusterRemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRemediationPolicyList.
func (in *ClusterRemediationPolicyList) DeepCopy() *ClusterRemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterRemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRemediationPolicySpec) DeepCopyInto(out *ClusterRemediationPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	out.ScenarioLibraryRef = in.ScenarioLibraryRef
	if in.ScenarioConfigs != nil {
		in, out := &in.ScenarioConfigs, &out.ScenarioConfigs
		*out = make([]ScenarioConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.GlobalConfig.DeepCopyInto(&out.GlobalConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRemediationPolicySpec.
func (in *ClusterRemediationPolicySpec) DeepCopy() *ClusterRemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRemediationPolicyStatus) DeepCopyInto(out *ClusterRemediationPolicyStatus) {
	*out = *in
	in.LastEvaluated.DeepCopyInto(&out.LastEvaluated)
	in.DetectionStats.DeepCopyInto(&out.DetectionStats)
	out.RemediationStats = in.RemediationStats
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRemediationPolicyStatus.
func (in *ClusterRemediationPolicyStatus) DeepCopy() *ClusterRemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionSpec) DeepCopyInto(out *DetectionSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(ResourceFilter)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(ThresholdSpec)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceFilter) DeepCopyInto(out *ResourceFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceFilter.
func (in *ResourceFilter) DeepCopy() *ResourceFilter {
	if in == nil {
		return nil
	}
	out := new(ResourceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionSpec.
func (in *DetectionSpec) DeepCopy() *DetectionSpec {
	if in == nil {
		return nil
	}
	out := new(DetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionStats) DeepCopyInto(out *DetectionStats) {
	*out = *in
	if in.ByScenario != nil {
		in, out := &in.ByScenario, &out.ByScenario
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionStats.
func (in *DetectionStats) DeepCopy() *DetectionStats {
	if in == nil {
		return nil
	}
	out := new(DetectionStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentationSpec) DeepCopyInto(out *DocumentationSpec) {
	*out = *in
	if in.RootCauses != nil {
		in, out := &in.RootCauses, &out.RootCauses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManualSteps != nil {
		in, out := &in.ManualSteps, &out.ManualSteps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentationSpec.
func (in *DocumentationSpec) DeepCopy() *DocumentationSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationSpec) DeepCopyInto(out *EscalationSpec) {
	*out = *in
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(NotifySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationSpec.
func (in *EscalationSpec) DeepCopy() *EscalationSpec {
	if in == nil {
		return nil
	}
	out := new(EscalationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalEscalationConfig) DeepCopyInto(out *GlobalEscalationConfig) {
	*out = *in
	if in.DefaultChannels != nil {
		in, out := &in.DefaultChannels, &out.DefaultChannels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalEscalationConfig.
func (in *GlobalEscalationConfig) DeepCopy() *GlobalEscalationConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalEscalationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalPolicyConfig) DeepCopyInto(out *GlobalPolicyConfig) {
	*out = *in
	if in.DefaultCooldown != nil {
		in, out := &in.DefaultCooldown, &out.DefaultCooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DefaultMaxRetries != nil {
		in, out := &in.DefaultMaxRetries, &out.DefaultMaxRetries
		*out = new(int)
		**out = **in
	}
	if in.Escalation != nil {
		in, out := &in.Escalation, &out.Escalation
		*out = new(GlobalEscalationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationChannels != nil {
		in, out := &in.NotificationChannels, &out.NotificationChannels
		*out = make([]NotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalPolicyConfig.
func (in *GlobalPolicyConfig) DeepCopy() *GlobalPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationChannel) DeepCopyInto(out *NotificationChannel) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationChannel.
func (in *NotificationChannel) DeepCopy() *NotificationChannel {
	if in == nil {
		return nil
	}
	out := new(NotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifySpec) DeepCopyInto(out *NotifySpec) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifySpec.
func (in *NotifySpec) DeepCopy() *NotifySpec {
	if in == nil {
		return nil
	}
	out := new(NotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterSpec) DeepCopyInto(out *ParameterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterSpec.
func (in *ParameterSpec) DeepCopy() *ParameterSpec {
	if in == nil {
		return nil
	}
	out := new(ParameterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ActionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Escalation != nil {
		in, out := &in.Escalation, &out.Escalation
		*out = new(EscalationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationStats) DeepCopyInto(out *RemediationStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationStats.
func (in *RemediationStats) DeepCopy() *RemediationStats {
	if in == nil {
		return nil
	}
	out := new(RemediationStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scenario) DeepCopyInto(out *Scenario) {
	*out = *in
	in.Detection.DeepCopyInto(&out.Detection)
	in.Remediation.DeepCopyInto(&out.Remediation)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]ParameterSpec, len(*in))
		copy(*out, *in)
	}
	in.Documentation.DeepCopyInto(&out.Documentation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scenario.
func (in *Scenario) DeepCopy() *Scenario {
	if in == nil {
		return nil
	}
	out := new(Scenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioConfig) DeepCopyInto(out *ScenarioConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int)
		**out = **in
	}
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioConfig.
func (in *ScenarioConfig) DeepCopy() *ScenarioConfig {
	if in == nil {
		return nil
	}
	out := new(ScenarioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioLibrary) DeepCopyInto(out *ScenarioLibrary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioLibrary.
func (in *ScenarioLibrary) DeepCopy() *ScenarioLibrary {
	if in == nil {
		return nil
	}
	out := new(ScenarioLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScenarioLibrary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioLibraryList) DeepCopyInto(out *ScenarioLibraryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScenarioLibrary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioLibraryList.
func (in *ScenarioLibraryList) DeepCopy() *ScenarioLibraryList {
	if in == nil {
		return nil
	}
	out := new(ScenarioLibraryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScenarioLibraryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioLibrarySpec) DeepCopyInto(out *ScenarioLibrarySpec) {
	*out = *in
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make(map[string]Scenario, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioLibrarySpec.
func (in *ScenarioLibrarySpec) DeepCopy() *ScenarioLibrarySpec {
	if in == nil {
		return nil
	}
	out := new(ScenarioLibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioLibraryStatus) DeepCopyInto(out *ScenarioLibraryStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioLibraryStatus.
func (in *ScenarioLibraryStatus) DeepCopy() *ScenarioLibraryStatus {
	if in == nil {
		return nil
	}
	out := new(ScenarioLibraryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSelector) DeepCopyInto(out *TargetSelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedNamespaces != nil {
		in, out := &in.ExcludedNamespaces, &out.ExcludedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceTypes != nil {
		in, out := &in.ResourceTypes, &out.ResourceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSelector.
func (in *TargetSelector) DeepCopy() *TargetSelector {
	if in == nil {
		return nil
	}
	out := new(TargetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdSpec) DeepCopyInto(out *ThresholdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdSpec.
func (in *ThresholdSpec) DeepCopy() *ThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioLibraryReference) DeepCopyInto(out *ScenarioLibraryReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioLibraryReference.
func (in *ScenarioLibraryReference) DeepCopy() *ScenarioLibraryReference {
	if in == nil {
		return nil
	}
	out := new(ScenarioLibraryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationTask) DeepCopyInto(out *RemediationTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationTask.
func (in *RemediationTask) DeepCopy() *RemediationTask {
	if in == nil {
		return nil
	}
	out := new(RemediationTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationTaskList) DeepCopyInto(out *RemediationTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationTaskList.
func (in *RemediationTaskList) DeepCopy() *RemediationTaskList {
	if in == nil {
		return nil
	}
	out := new(RemediationTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationTaskSpec) DeepCopyInto(out *RemediationTaskSpec) {
	*out = *in
	out.Target = in.Target
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]TaskAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationTaskSpec.
func (in *RemediationTaskSpec) DeepCopy() *RemediationTaskSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationTaskStatus) DeepCopyInto(out *RemediationTaskStatus) {
	*out = *in
	if in.ClaimedAt != nil {
		in, out := &in.ClaimedAt, &out.ClaimedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(TaskResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationTaskStatus.
func (in *RemediationTaskStatus) DeepCopy() *RemediationTaskStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskAction) DeepCopyInto(out *TaskAction) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskAction.
func (in *TaskAction) DeepCopy() *TaskAction {
	if in == nil {
		return nil
	}
	out := new(TaskAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTarget) DeepCopyInto(out *TaskTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTarget.
func (in *TaskTarget) DeepCopy() *TaskTarget {
	if in == nil {
		return nil
	}
	out := new(TaskTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskResult) DeepCopyInto(out *TaskResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskResult.
func (in *TaskResult) DeepCopy() *TaskResult {
	if in == nil {
		return nil
	}
	out := new(TaskResult)
	in.DeepCopyInto(out)
	return out
}
